### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 494

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#72] opened 2016-08-18 09:59 UTC
Description: 
While the style sheets are still disabled, 'select' Structure then fieldsets/labels. Visually check any date input fields contain the screen reader help text for the date format input.

Expected: 
Date format input is part of the label of the date field on the page

Actual: 
Date fields appear on the css with no screen reader help text.

**Comment by marklunn** [comment] 2016-08-18 10:00
![bug_494_clb_picture_123](https://cloud.githubusercontent.com/assets/13219344/17769908/e73cf82c-6532-11e6-9ba5-4c2e736b552a.jpeg)
![bug_494_clb_picture_159](https://cloud.githubusercontent.com/assets/13219344/17769914/e94ea6e2-6532-11e6-8806-e61031c8ae50.jpeg)

**Comment by ijdickinson** [comment] 2016-08-19 17:39
Duplicate of #81

**Closed by ijdickinson** 2016-08-19 17:39 UTC
Labels: invalid
