### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 488

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#67] opened 2016-08-12 12:21 UTC
landing page contains 2 level 1 headings - see attached
![defect488](https://cloud.githubusercontent.com/assets/6670586/17622012/9ee13e32-608f-11e6-870f-dfd603e9f06e.jpeg)

**Comment by ijdickinson** [comment] 2016-08-19 17:46
Duplicate of #82

**Closed by ijdickinson** 2016-08-19 17:46 UTC
Labels: invalid
