### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 489

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ukhpi#68] opened 2016-08-12 12:26 UTC
If the link opens in a new window, check that the link has the new window icon and tooltips text to warn the user. 

On landing page feedback link has no tooltips to warn user

**Comment by ijdickinson** [comment] 2016-08-19 17:44
Duplicate of #83

**Closed by ijdickinson** 2016-08-19 17:44 UTC
Labels: invalid
