### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 502

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#76] opened 2016-08-18 10:10 UTC
Description: 
If the link opens in a new window, check that the link has the new window icon and tooltips text to warn the user. 

If in doubt check the clarification in the comments of this test.

Expected: 
New window links are correctly identified.

Actual: 
Feedback link opens a new window and no prior warning given to user

**Comment by marklunn** [comment] 2016-08-18 10:11
![bug_502_clb_picture_132](https://cloud.githubusercontent.com/assets/13219344/17770221/6af401d2-6534-11e6-8639-b4fe5850c555.jpeg)

**Comment by ijdickinson** [comment] 2016-08-19 17:34
duplicate of #83

**Closed by ijdickinson** 2016-08-19 17:34 UTC
Labels: invalid
