### ISSUE TITLE
Alter ‘West Midlands Region' map caption to 'West Midlands' 

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#12] opened 2016-05-25 15:01 UTC
None of the others have ‘Region’ in that text. Also the map caption for the area also contains ‘Region’ and others do not.

**Comment by lrmrthomas** [comment] 2016-06-03 14:04
Explained to me why 'Region' is in the header text as it is in the data to distinguish it from the West Midlands local authority so happy with this.

This change should now be to make the map caption consistent with the radio button text, so remove 'Region' from the map text.

**Comment by ijdickinson** [comment] 2016-06-03 18:26
I can't easily change the caption on the map, since that label is taken directly from the data. So I have changed the selection control to have the same name as the region label in the data.

**Comment by lrmrthomas** [comment] 2016-06-06 07:10
Didn't realise the map captions taken from the data, happy with the explanation. Happy with the resolution as I can confirm the radio button caption is now consistent with the map caption. Closing this issue

**Closed by lrmrthomas** 2016-06-06 07:10 UTC
Labels: bug, waiting for qa
