### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 495

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#73] opened 2016-08-18 10:01 UTC
Description: 
Examine the outline view to ensure that: 

Headings and Page Title are present, 
The headings are nested correctly, and 
The headings provide an effective overview of the contents of the page.

Expected: 
Heading structure is correct. 

Remember to close the outline view window.

Actual: 
Headings incorrectly nested with two H1 headings.

**Comment by marklunn** [comment] 2016-08-18 10:06
![bug_495_clb_picture_125](https://cloud.githubusercontent.com/assets/13219344/17770083/c74577b4-6533-11e6-9aeb-cd0106800a7f.jpeg)
![bug_495_clb_picture_162](https://cloud.githubusercontent.com/assets/13219344/17770087/cc5dd638-6533-11e6-8e64-fc385bb3575e.jpeg)

**Comment by ijdickinson** [comment] 2016-08-19 17:37
Duplicate of #82

**Closed by ijdickinson** 2016-08-19 17:37 UTC
Labels: invalid
