### ISSUE TITLE
Update qonsole sample queries

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#51] opened 2016-06-09 15:45 UTC

**Comment by bwmcbride** [comment] 2016-06-09 15:58
Is this  a duplicate of https://github.com/epimorphics/lr-landing/issues/1

**Comment by ijdickinson** [comment] 2016-06-09 16:07
Actually that may be un Herring Rouge (gitlab, not github)

**Comment by bwmcbride** [comment] 2016-06-09 16:09
I or you can just delete the old one if that's easier

**Comment by ijdickinson** [comment] 2016-06-10 09:04
It's easier to leave that other ticket in place so that I can properly associate the commit with the issue. Update deployed now.

**Comment by MalcolmShazell** [comment] 2016-06-11 13:17
confirm done

**Closed by MalcolmShazell** 2016-06-11 13:17 UTC
Labels: enhancement, waiting for qa
