### ISSUE TITLE
DEFAULT.QC_Accessibility_Eservices - Defect # 506 - validation warnings

### ISSUE THREAD

**Issue by marklunn** [epimorphics/ukhpi#79] opened 2016-08-18 10:14 UTC
Description: 
From the accessibility toolbar 'select' Check followed by W3C HTML Validator followed by Validate HTML [new window].

Expected: 
A new window will open with the results of the check:

Red Banner with errors = Fail
Green Banner with 'Tentative' in the banner = Fail
Green Banner with 'Success' in the banner = Pass

Actual: 
fails validation - report attached

**Comment by marklunn** [comment] 2016-08-18 10:15
[BUG_506_data selectNu Html Checker.docx](https://github.com/epimorphics/ukhpi/files/424633/BUG_506_data.selectNu.Html.Checker.docx)
[BUG_506_Nu Html Checker - Data select criteria.docx](https://github.com/epimorphics/ukhpi/files/424634/BUG_506_Nu.Html.Checker.-.Data.select.criteria.docx)

**Comment by ijdickinson** [comment] 2016-08-19 17:28
This is quite a list. Going through it:

* **First document**
* 1-1 - accepted, but the error is entirely benign
* 1-2 - this is actually text required by Google+, but since we're not using that service I will remove it
* 1-3 - rejected: pre-HTML5 browsers will treat unknown elements as `div`s, in which case the Aria role adds useful information
* 1-4 - rejected - see item 1-3
* 1-5 - rejected: descendant inputs of label elements do not need `for` attributes. See http://w3c.github.io/html/sec-forms.html#the-label-element
* 1-6 - duplicate of item 1-5
* 1-7 - not a validation failure
* 1-8 - not a validation failure
* 1-9 - this is only a warning, but I will investigate
* 1-10 - see item 1-3
* 1-11 - this is only a warning, but I will investigate
* **Second document**
* 2-1 - duplicate of 1-2
* 2-2 - rejected, see above 1-3
* 2-3 - rejected, see 2-2
* 2-4 - accepted, will investigate
* 2-5 - rejected, see 1-5
* 2-6 - duplicate of 2-4
* 2-7 - rejected see 2-2
* 2-8 & 2-9 - error report does not match source code. Please state *exactly* what was being tested.
* 2-10 & 2-11 - error report does not match source code. Please state *exactly* what was being tested.
* 2-12 - warning only 
* 2-13 - duplicate of 2-12
* 2-14 & 2-15 - error report does not match source code. Please state *exactly* what was being tested.
* 2-16 - duplicate warning
* 2-17 & 2-18 - error report does not match source code. Please state *exactly* what was being tested.
* 2-19 - duplicate warning
* 2-20 & 2-21 - error report does not match source code. Please state *exactly* what was being tested.
* 2-22 - duplicate warning
* 2-23 & 2-24 - error report does not match source code. Please state *exactly* what was being 
tested.
* 2-25 - duplicate warning
* 2-26 & 2-27 - error report does not match source code. Please state *exactly* what was being tested.
* 2-28 - duplicate warning
* 2-29 - 2-46 - these are all duplicates of the above. Was it really necessary to repeat them?
* 2-47 - 2.49 - duplicates from document 1

**Comment by ijdickinson** [comment] 2016-08-25 12:36
Correction on 1-5 and 1-6: there is an instance of a mismatched for/id pair. Factored out as issue #93

**Comment by ijdickinson** [comment] 2016-08-25 13:54
1-1 and 1-2 have now been addressed by issue #66

**Comment by ijdickinson** [comment] 2016-08-25 14:18
1-9 has been addressed by issue #94

**Comment by MalcolmShazell** [comment] 2017-07-19 15:59
Will close this as obsolete due to redesign

**Closed by MalcolmShazell** 2017-07-19 15:59 UTC
Labels: question
